# Generated by Django 5.2.17 on 2026-10-03 12:25

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.conciliaciones.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("comunidades", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Conciliacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("anio", models.PositiveSmallIntegerField(verbose_name="año")),
                (
                    "mes",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ]
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("importada", "Saldo inicial importado"),
                            ("borrador", "Borrador"),
                            ("procesada", "Procesada"),
                            ("cerrada", "Cerrada"),
                        ],
                        default="borrador",
                        max_length=12,
                    ),
                ),
                ("saldo_anterior", models.BigIntegerField(default=0)),
                ("total_ingresos", models.BigIntegerField(default=0)),
                ("total_egresos", models.BigIntegerField(default=0)),
                ("redondeo", models.BigIntegerField(default=0)),
                ("saldo_banco", models.BigIntegerField(blank=True, null=True)),
                ("advertencias", models.JSONField(blank=True, default=list)),
                ("creada_en", models.DateTimeField(auto_now_add=True)),
                ("procesada_en", models.DateTimeField(blank=True, null=True)),
                ("cerrada_en", models.DateTimeField(blank=True, null=True)),
                (
                    "cerrada_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "creada_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "cuenta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="conciliaciones",
                        to="comunidades.cuentabancaria",
                    ),
                ),
            ],
            options={
                "verbose_name": "conciliación",
                "verbose_name_plural": "conciliaciones",
                "ordering": ["cuenta", "-anio", "-mes"],
            },
        ),
        migrations.CreateModel(
            name="ArchivoCargado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("ingresos", "Planilla de ingresos"),
                            ("egresos", "Planilla de egresos"),
                            ("cartola", "Cartola bancaria"),
                            ("apertura", "Planilla de conciliación (saldo inicial)"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "archivo",
                    models.FileField(
                        max_length=500, upload_to=apps.conciliaciones.models._ruta_archivo
                    ),
                ),
                ("nombre_original", models.CharField(max_length=255)),
                ("sha256", models.CharField(max_length=64)),
                ("tamano", models.PositiveIntegerField(verbose_name="tamaño (bytes)")),
                ("subido_en", models.DateTimeField(auto_now_add=True)),
                (
                    "subido_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "conciliacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="archivos",
                        to="conciliaciones.conciliacion",
                    ),
                ),
            ],
            options={
                "verbose_name": "archivo cargado",
                "verbose_name_plural": "archivos cargados",
            },
        ),
        migrations.CreateModel(
            name="Evento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "accion",
                    models.CharField(
                        choices=[
                            ("importada", "Saldo inicial importado"),
                            ("creada", "Conciliación creada"),
                            ("archivo", "Archivo cargado"),
                            ("procesada", "Procesada"),
                            ("cruce_confirmado", "Cruce confirmado"),
                            ("cruce_deshecho", "Cruce deshecho"),
                            ("cruce_manual", "Cruce manual"),
                            ("cerrada", "Cerrada"),
                            ("reabierta", "Reabierta"),
                        ],
                        max_length=20,
                    ),
                ),
                ("detalle", models.TextField(blank=True)),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                (
                    "conciliacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eventos",
                        to="conciliaciones.conciliacion",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Movimiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "origen",
                    models.CharField(
                        choices=[
                            ("periodo", "De la cartola del período"),
                            ("arrastre", "No contabilizado de meses anteriores"),
                            ("repetido", "Repetido de la cartola anterior (descartado)"),
                        ],
                        max_length=8,
                    ),
                ),
                ("fecha", models.DateField()),
                ("descripcion", models.CharField(blank=True, max_length=255)),
                ("monto", models.BigIntegerField()),
                ("es_cargo", models.BooleanField()),
                ("documento", models.CharField(blank=True, max_length=40)),
                ("sucursal", models.CharField(blank=True, max_length=60)),
                (
                    "conciliacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movimientos",
                        to="conciliaciones.conciliacion",
                    ),
                ),
            ],
            options={
                "ordering": ["fecha", "id"],
            },
        ),
        migrations.CreateModel(
            name="Partida",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("INGRESO", "Ingreso"), ("EGRESO", "Egreso")], max_length=7
                    ),
                ),
                (
                    "origen",
                    models.CharField(
                        choices=[
                            ("periodo", "Del período"),
                            ("arrastre", "Pendiente de meses anteriores"),
                        ],
                        max_length=8,
                    ),
                ),
                ("comprobante", models.IntegerField(blank=True, null=True)),
                ("fecha", models.DateField(blank=True, null=True)),
                ("monto", models.BigIntegerField()),
                ("glosa", models.TextField(blank=True)),
                ("depto", models.CharField(blank=True, max_length=40)),
                ("cheque", models.CharField(blank=True, max_length=40)),
                (
                    "conciliacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partidas",
                        to="conciliaciones.conciliacion",
                    ),
                ),
            ],
            options={
                "ordering": ["tipo", "fecha", "comprobante"],
            },
        ),
        migrations.CreateModel(
            name="Cruce",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("cheque", "Nº de cheque"),
                            ("monto_fecha", "Monto y fecha"),
                            ("sugerido", "Sugerido (revisar)"),
                            ("manual", "Manual"),
                        ],
                        max_length=12,
                    ),
                ),
                ("nota", models.CharField(blank=True, max_length=255)),
                ("confirmado", models.BooleanField(default=False)),
                ("confirmado_en", models.DateTimeField(blank=True, null=True)),
                (
                    "conciliacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cruces",
                        to="conciliaciones.conciliacion",
                    ),
                ),
                (
                    "confirmado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "movimiento",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cruce",
                        to="conciliaciones.movimiento",
                    ),
                ),
                (
                    "partida",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cruce",
                        to="conciliaciones.partida",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="conciliacion",
            constraint=models.UniqueConstraint(
                fields=("cuenta", "anio", "mes"), name="una_conciliacion_por_cuenta_y_mes"
            ),
        ),
        migrations.AddConstraint(
            model_name="archivocargado",
            constraint=models.UniqueConstraint(
                fields=("conciliacion", "tipo"), name="un_archivo_por_tipo_y_conciliacion"
            ),
        ),
    ]
