# Generated by Django 5.2.17 on 2026-10-03 14:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conciliaciones", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evento",
            name="accion",
            field=models.CharField(
                choices=[
                    ("importada", "Saldo inicial importado"),
                    ("creada", "Conciliación creada"),
                    ("archivo", "Archivo cargado"),
                    ("procesada", "Procesada"),
                    ("cruce_confirmado", "Cruce confirmado"),
                    ("cruce_deshecho", "Cruce deshecho"),
                    ("cruce_manual", "Cruce manual"),
                    ("redondeo", "Redondeo ajustado"),
                    ("cerrada", "Cerrada"),
                    ("reabierta", "Reabierta"),
                ],
                max_length=20,
            ),
        ),
    ]
