# Generated by Django 5.2.17 on 2026-10-03 20:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conciliaciones", "0002_evento_redondeo"),
    ]

    operations = [
        migrations.AddField(
            model_name="conciliacion",
            name="cartola_desde",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="conciliacion",
            name="cartola_hasta",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="conciliacion",
            name="cartola_numero",
            field=models.CharField(blank=True, max_length=20, verbose_name="nº de cartola"),
        ),
    ]
