# Generated by Django 5.2.17 on 2026-10-07 16:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conciliaciones", "0003_datos_cartola"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movimiento",
            name="origen",
            field=models.CharField(
                choices=[
                    ("periodo", "De la cartola del período"),
                    ("arrastre", "No contabilizado de meses anteriores"),
                    ("repetido", "Repetido de la cartola anterior (descartado)"),
                    ("diferencia", "Diferencia de cobro de cheque"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="partida",
            name="origen",
            field=models.CharField(
                choices=[
                    ("periodo", "Del período"),
                    ("arrastre", "Pendiente de meses anteriores"),
                    ("diferencia", "Diferencia de cobro de cheque"),
                ],
                max_length=10,
            ),
        ),
    ]
