# Generated by Django 5.2.17 on 2026-10-07 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conciliaciones", "0004_origen_diferencia"),
    ]

    operations = [
        migrations.AddField(
            model_name="cruce",
            name="grupo",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name="cruce",
            name="movimiento",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cruces",
                to="conciliaciones.movimiento",
            ),
        ),
        migrations.AlterField(
            model_name="cruce",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("cheque", "Nº de cheque"),
                    ("monto_fecha", "Monto y fecha"),
                    ("sugerido", "Sugerido (revisar)"),
                    ("agrupado", "Agrupado (revisar)"),
                    ("manual", "Manual"),
                ],
                max_length=12,
            ),
        ),
    ]
