# Generated by Django 5.2.17 on 2026-10-03 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Comunidad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("nombre", models.CharField(max_length=200, unique=True)),
                ("rut", models.CharField(blank=True, max_length=12, verbose_name="RUT")),
                (
                    "direccion",
                    models.CharField(blank=True, max_length=255, verbose_name="dirección"),
                ),
                ("activa", models.BooleanField(default=True)),
                ("creada_en", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "comunidades",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="CuentaBancaria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "banco",
                    models.CharField(
                        choices=[
                            ("santander", "Santander"),
                            ("bci", "BCI"),
                            ("chile", "Banco de Chile"),
                            ("estado", "BancoEstado"),
                            ("itau", "Itaú"),
                            ("scotiabank", "Scotiabank"),
                            ("security", "Security"),
                            ("otro", "Otro"),
                        ],
                        max_length=20,
                    ),
                ),
                ("numero", models.CharField(max_length=40, verbose_name="número de cuenta")),
                ("activa", models.BooleanField(default=True)),
                (
                    "comunidad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cuentas",
                        to="comunidades.comunidad",
                    ),
                ),
            ],
            options={
                "verbose_name": "cuenta bancaria",
                "verbose_name_plural": "cuentas bancarias",
                "ordering": ["comunidad__nombre", "banco"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("banco", "numero"), name="cuenta_unica_por_banco"
                    )
                ],
            },
        ),
    ]
